// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApgZFAymBiWW8MFjV1dnBPLiOFQZ5jxWM',
    appId: '1:544499278167:android:14f4f457c51587962d1e12',
    messagingSenderId: '544499278167',
    projectId: 'meinhause-user',
    storageBucket: 'meinhause-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKEvnqkKeq9NR-oAw6AiSNhCwA5GAWNIo',
    appId: '1:544499278167:ios:9b2b8a445e825e822d1e12',
    messagingSenderId: '544499278167',
    projectId: 'meinhause-user',
    storageBucket: 'meinhause-user.appspot.com',
    androidClientId: '544499278167-qr79aquvomnpfhit5ot7i3orbvop0var.apps.googleusercontent.com',
    iosClientId: '544499278167-2e9su12l1h2js64g29dgdu6ks1spnfrq.apps.googleusercontent.com',
    iosBundleId: 'ca.meinhaus.user.app',
  );
}
